swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/UserProfileResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile updated successully
          schema:
            $ref: "#/definitions/UserProfileResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all transactions
      description: Returns all transactions for the authenticated user
      parameters:
        - in: query
          name: userId
          description: ID of the user to fetch transactions for
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: A list of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Add a new transaction
      description: Adds a new transaction for the authenticated user
      parameters:
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: "#/definitions/TransactionInput"
      produces:
        - application/json
      responses:
        "201":
          description: Transaction created successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions/current-month:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get current month transactions
      description: Returns transactions for the authenticated user for the current month
      parameters:
        - in: query
          name: accountType
          description: Type of the account
          required: true
          type: string
        - in: query
          name: userId
          description: ID of the user
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: A list of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction details
      description: Returns the details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to fetch
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update a transaction
      description: Updates the category and notes of an existing transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdateInput"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete a transaction
      description: Deletes a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        "204":
          description: Transaction deleted successfully
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserProfileResponse:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
      body:
        type: object
        properties:
          firstName:
            type: string
          lastName:
            type: string
          email:
            type: string
          checkingBalance:
            type: number
          savingsBalance:
            type: number
          creditBalance:
            type: number
  Transaction:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      amount:
        type: number
      type:
        type: string
      description:
        type: string
      date:
        type: string
        format: date-time
      accountType:
        type: string
      balanceAfterTransaction:
        type: number
      category:
        type: string
      notes:
        type: string
  TransactionInput:
    type: object
    required:
      - amount
      - type
      - description
      - userId
      - accountType
    properties:
      amount:
        type: number
      type:
        type: string
      description:
        type: string
      userId:
        type: string
      accountType:
        type: string
  TransactionUpdateInput:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
